Uchet/Controllers/OwnerPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Uchet.Data;
using Uchet.Models;

namespace Uchet.Controllers
{
    public class OwnerPanelController : Controller
    {
        private ApplicationDbContext db;
        private readonly UserManager<IdentityUser> _userManager;

        public OwnerPanelController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            db = context;
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult CreateShop() {//Просто возвращает страницу создания магазина
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateShop(Shop shop) //обрабатывает добавление нового магазина
        {
            var user = await _userManager.GetUserAsync(User);
            var email = user.Email;
            shop.OwnerEmail = email;
            db.Shops.Add(shop);
            await db.SaveChangesAsync();
            return RedirectToAction("MyShops");
        }

        public async Task<IActionResult> MyShops() //выводит все магазины конкретного пользователя
        {
            var shops = db.Shops.ToList();
            var user = await _userManager.GetUserAsync(User);
            var email = user.Email;
            var MyShops = from s in shops
                          where s.OwnerEmail == email
                          select s;
            return View(MyShops);
        }

        [Authorize]
        public async Task<IActionResult> AddProduct()
        {
            //получаем список магазинов текущего пользвателя
            var shops = db.Shops.ToList();
            var user = await _userManager.GetUserAsync(User);
            var email = user.Email;
            var MyShops = from s in shops
                          where s.OwnerEmail == email
                          select s;
            //получили список магазинов

            //отправляем на страницу добавления продукта список магазинов данного пользователя
            //чтобы он мог выбрать конкретно из своего списока магазинов, куда добавить товар
            ViewBag.Shops = new SelectList(MyShops, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(Product product)
        {

            ////получаем список магазинов текущего пользвателя
            //var shops = db.Shops.ToList();
            //var user = await _userManager.GetUserAsync(User);
            //var email = user.Email;
            //var MyShops = from s in shops
            //              where s.OwnerEmail == email
            //              select s;
            ////получили список магазинов
            db.Add(product);
            await db.SaveChangesAsync();
            //Shop shop = MyShops.FirstOrDefault(c => c.Id == product.ShopId);
            return RedirectToAction("AllProducts");
        }

        [Authorize]
        public IActionResult AddEmployee()
        {
            return View();
        }
    }
}

Uchet/Views/OwnerPanel/AddEmployee.cshtml
@{
    ViewData["Title"] = "AddEmployee";
    Layout = "~/Views/OwnerPanel/_OwnerPanelLayout.cshtml";
}

<h1>Добавить сотрудника</h1>

Uchet/Views/OwnerPanel/AddProduct.cshtml
@model Uchet.Models.Product
@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Views/OwnerPanel/_OwnerPanelLayout.cshtml";
}

<h1>Добавить товар</h1>

<div class="row">
    <div class="col-4">
        <form asp-action="AddProduct" asp-controller="OwnerPanel">
            <div class="form-group">
                <label asp-for="ShopId">Выберите магазин, куда добавить товар:</label>
                <select asp-for="ShopId" asp-items="ViewBag.Shops"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название товара</label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание товара</label>
                <textarea type="text" asp-for="Description" class="form-control" /></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">Категория товара</label>
                <input type="text" asp-for="Category" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="QuantityStock" class="control-label">Количество на складе</label>
                <input type="text" asp-for="QuantityStock" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PurchasePrice" class="control-label">Закупочная цена</label>
                <input type="text" asp-for="PurchasePrice" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SalePrice" class="control-label">Цена продажи</label>
                <input type="text" asp-for="SalePrice" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить товар" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

Uchet/Views/OwnerPanel/CreateShop.cshtml
@model Uchet.Models.Shop
@{
    ViewData["Title"] = "Создать магазин";
    Layout = "~/Views/OwnerPanel/_OwnerPanelLayout.cshtml";
}

<h1>Создать магазин</h1>
<div class="row">
    <div class="col-4">
        <form asp-action="CreateShop" asp-controller="OwnerPanel">
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название магазина</label>
                <input type="text" asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание магазина</label>
                <input type="text" asp-for="Description" class="form-control" />
            </div>

            <div class="form-group">
                <input type="submit" value="Создать магазин" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

Uchet/Views/OwnerPanel/Index.cshtml
@{
    ViewData["Title"] = "Мои Магазины";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Страница владельца магазина</h1>

Uchet/Views/OwnerPanel/MyShops.cshtml
@model IEnumerable<Uchet.Models.Shop>
@{
    ViewData["Title"] = "MyShops";
    Layout = "~/Views/OwnerPanel/_OwnerPanelLayout.cshtml";
}

<h1 style="display:inline-block;">Мои магазины</h1>
<a asp-action="CreateShop" class="btn btn-outline-success" style="vertical-align: super;">Добавить еще магазин</a>
<ol>
    @foreach (var shop in Model)
    {
        <li>
            <b>@shop.Name</b> - <b>@shop.Description</b>
        </li>
    }
</ol>

Uchet/Views/OwnerPanel/_OwnerPanelLayout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Касса и Склад</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Касса и Склад</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Features">Возможности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Pricing">Тарифы</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Касса и Склад
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>